# Generated by Django 5.1 on 2025-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Montclair', max_length=200),
        ),
    ]
